### ISSUE TITLE
GHC versions covered by AppVeyor CI

### ISSUE THREAD

**Issue by adamgundry** [acid-state/acid-state#143]
Looking at https://ci.appveyor.com/project/stepcut/acid-state it appears AppVeyor is running CI with GHC 8.2 and 8.4. In contrast the Linux CI has everything from 7.10 to 9.2. Perhaps some more recent versions should be included on AppVeyor?

**Comment by andreasabel** [comment]
> Perhaps some more recent versions should be included on AppVeyor?

I suppose so, but I have never used AppVeyor. 
I think it could be tried to extend the AppVeyor matrix.  If this does not work well, we could also try a GHA workflow for windows (and macOS).  [But maybe we need not actively work towards a GHA monopoly.]
https://github.com/acid-state/acid-state/blob/9d9efd9c64178044cd88dc82d10137b94aae9829/appveyor.yml#L6-L14

**Comment by stepcut** [comment]
I think the primary reason for using appveyor at all is to ensure that the build works on Windows. That is somewhat important since we do have windows specific code in `src-win32`.

I don't think we need to test against every version of GHC on Windows like we do on Linux.

It is definitely annoying that the 8.2.2 is always failing on Appveyor at the moment.

I'd be fine with just testing GHC 9.2 on Windows. But I have no idea how to do that. 

I am not opposed to also testing on OS X, but it seems less important since it uses the same code as Linux.

I have no opinion on appveyor vs github workflows vs other.

**Comment by andreasabel** [comment]
Historically, I think AppVeyor was the tool of choice for a Windows CI due to limited availability of alternatives.

A GHA CI could be similar to this: https://github.com/haskell/text-icu/blob/52822ec7684e39d3ee5afcd0d807f902971c0761/.github/workflows/cabal-mac-win.yml
