### ISSUE TITLE
Provide lens compatible typeclasses.

### ISSUE THREAD

**Issue by fhaust** [acid-state/acid-state#28]
(This is a followup to my question on SO: http://stackoverflow.com/questions/20686215/how-to-zoom-in-acid-state )

It would be great if you could provide instances to make acid-states `Update` and `Query` Monads compatible with the `lens` ecosystem. Specifically the `Zoomed` instance, but there are probably other useful things in there.

J Abrahamson (on SO) pointed out that it is not possible to do this without exposing some of `acid-state`s internals or having it depend on `lens` (which should be prevented). Maybe you could cooperate with the lens team to find a better solution?

**Comment by stepcut** [comment]
I don't see a way to provide a Zoomed instance with out depending on lens -- and depending on lens is a pretty big dependency for something most people will not actually use. If we can make an `acid-state-lens` package, that seems better. Apparently that might involve exporting some internals from `acid-state`?

**Comment by adamgundry** [comment]
Since f6bd2c6dea66d3bbdf2b2566e9278e4e35f64b27 exposes the definition of `Update`, it should be possible to write an orphan `Zoomed` instance downstream. Given that we don't want `acid-state` to depend on `lens`, I don't think there is anything else we can do. If someone wants to make an `acid-state-lens` package, feel free (though there is a bigger reorganisation pending, see #99).

**Comment by fhaust** [comment]
Oh ... it's been a while :-)

I think you can write lens instances without depending on the lens package, but honestly I don't care anymore.
