### ISSUE TITLE
acid-state may not restart if killed with kill 9-

### ISSUE THREAD

**Issue by pierreMizrahi** [acid-state/acid-state#89]
Acid state uses a a PID file to ensure being a singleton. Unfortunately,the following sequence does not allow for an automatic recovery:

- kill  the process instance with kill -9
- have another, unrelated process take the same process ID while the program using acid-state is down
- restart the program using acid-state

(to simulate this, one can manually modify the PID in the lock file to usurp the one of an existing, unrelated process)

The occurrence of this sequence of events is unfortunately high at machine reboot: it happened to us in production during a disaster recovery test that simulates a power outage.

A possibility would be to use a unix socket rather than a PID file, or alternatively to use flock(2). This seems to be possible, since the win32 and linux implementations are already different, but I did not checked in much details.

Some discussion around this topic can be found here:

https://stackoverflow.com/questions/220525/ensure-a-single-instance-of-an-application-in-linux/221159
https://stackoverflow.com/questions/5339200/how-to-create-a-single-instance-application-in-c-or-c

**Comment by pierreMizrahi** [comment]
Pull request: #90

**Comment by gromakovsky** [comment]
I have a question which might be silly, but still: why not use [filelock](https://hackage.haskell.org/package/filelock-0.1.1.2/docs/System-FileLock.html) library?

We have the same problem and I wanted to try `filelock` before I saw this issue.
@pierreMizrahi did you consider using `filelock`? It uses `flock(2)` on linux and it's crossplatform, so there would be no need to have `src-unix` and `src-win32`.

**Comment by pierreMizrahi** [comment]
I briefly considered it, and I confess that I offered the socket implementation because:
- that's what we do most often and I don't know a lot about flock (and even less on the windows version, which I won't be able to test)
- that's what I use in my local fork
- I felt that adding another dependency was more impacting

If there is some consensus and a volunteer to test on windows, I can try to make a filelock version

**Comment by gromakovsky** [comment]
@pierreMizrahi thanks for the answer. We decided to use `filelock`, because it's crossplatform and allowed us to decrease amount of code in `acid-state`. We tested it on Mac, Linux and Windows and it worked. It's done here: https://github.com/serokell/acid-state/pull/4
I don't know what `acid-state` maintainers will prefer, now there is a choice :)
We are using our fork anyway.

**Comment by dcoutts** [comment]
@gromakovsky can you make an upstream PR for this change please? It'd be better to propose these changes upstream properly and get public review etc and not maintain our own fork.

**Comment by gromakovsky** [comment]
Is `acid-state` maintained nowadays? I don't think it will be reviewed. Anyway, we can make an upstream PR.

**Comment by gromakovsky** [comment]
https://github.com/acid-state/acid-state/pull/91

**Comment by ddssff** [comment]
I would say that acid-state is maintained, though not always promptly.  I'm puzzled by how difficult it is to find out on github exactly who has commit privs - I know @stepcut does.

**Comment by dmjio** [comment]
@gromakovsky if you propose it, I'll review it, and commit it.

**Comment by stepcut** [comment]
`filelock` seems like a pretty lightweight dependency. `filelock` itself does not depend on any packages we do not already depend on anyway. So I am not concerned about adding it as a dependency. 

I would lean towards the `filelock` solution for the following 2 reasons:

  - it sounds like it has been tested in `acid-state` somewhat extensively already

  - because other people are using `filelock` there is a greater chance of people finding and fixing bugs in that code than in code which only resides in `acid-state`

Any other factors we should consider?

**Comment by pierreMizrahi** [comment]
I see no reason not to use filelock for this use case. This patch is clearly an improvement over both the current situation and my proposal.
