### ISSUE TITLE
Test suite?

### ISSUE THREAD

**Issue by parsonsmatt** [acid-state/acid-state#95]
I can't find a test suite for `acid-state` in this repository. Is the library untested?

**Comment by ddssff** [comment]
A test suite would certainly be a comfort.

**Comment by stepcut** [comment]
I believe acid-state predates the Cabal test-suite functionality. So there are some 'tests' in the 'examples' function, but to a large degree it is untested. I do believe this is one reason why acid-state is not more actively developed -- how do you know if you broke it?

Adding a test suite and a benchmark suite so that we can be sure new features and improvements aren't causing trouble is probably the top priority at the moment, IMO. With out those things every change is scary.

**Comment by adamgundry** [comment]
I'm planning to work on this, at least as far as getting the examples to build and doing some basic sanity checks that everything looks plausible.

**Comment by parsonsmatt** [comment]
FWIW, my PR (#94) introduces an `hspec` test-suite to cover the changes I've made  in that PR. I'll try and get that updated today to work with CI with 7.6.3 support.

**Comment by adamgundry** [comment]
Fixed by #98.
